name: Trigger AWS Glue Job

on:
  push:
    branches:
      - main

jobs:
  run-glue:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Start Glue Job
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        GLUE_JOB_NAME: ${{ secrets.GLUE_JOB_NAME }}
      run: |
        aws glue start-job-run --job-name "$GLUE_JOB_NAME" --region "$AWS_REGION"
